package me.kroppeb.aoc.helpers

import me.kroppeb.aoc.helpers.point.Point
import me.kroppeb.aoc.helpers.point.Point3D

fun msoa(): MutableSet<Any> = mutableSetOf()
fun <T> msot(): MutableSet<T> = mutableSetOf()
fun soi(vararg a: Int): Set<Int> = setOf(*a.toTypedArray())
fun msoi(vararg a: Int): MutableSet<Int> = mutableSetOf(*a.toTypedArray())
fun sol(vararg a: Long): Set<Long> = setOf(*a.toTypedArray())
fun msol(vararg a: Long): MutableSet<Long> = mutableSetOf(*a.toTypedArray())
fun sop(vararg a: Point): Set<Point> = setOf(*a)
fun msop(vararg a: Point): MutableSet<Point> = mutableSetOf(*a)
fun sop3(vararg a: Point3D): Set<Point3D> = setOf(*a)
fun msop3(vararg a: Point3D): MutableSet<Point3D> = mutableSetOf(*a)

fun mmoaa(): MutableMap<Any, Any> = mutableMapOf()
fun <T> mmoat(): MutableMap<Any, T> = mutableMapOf()
fun <K, V> mmokv(): MutableMap<K, V> = mutableMapOf()

fun moii(vararg a: Pair<Int, Int>): Map<Int, Int> = mapOf(*a)
fun mmoii(vararg a: Pair<Int, Int>): MutableMap<Int, Int> = mutableMapOf(*a)
fun moil(vararg a: Pair<Int, Long>): Map<Int, Long> = mapOf(*a)
fun mmoil(vararg a: Pair<Int, Long>): MutableMap<Int, Long> = mutableMapOf(*a)
fun moip(vararg a: Pair<Int, Point>): Map<Int, Point> = mapOf(*a)
fun mmoip(vararg a: Pair<Int, Point>): MutableMap<Int, Point> = mutableMapOf(*a)
fun moip3(vararg a: Pair<Int, Point3D>): Map<Int, Point3D> = mapOf(*a)
fun mmoip3(vararg a: Pair<Int, Point3D>): MutableMap<Int, Point3D> = mutableMapOf(*a)
fun moia(vararg a: Pair<Int, Any>): Map<Int, Any> = mapOf(*a)
fun mmoia(vararg a: Pair<Int, Any>): MutableMap<Int, Any> = mutableMapOf(*a)

fun moli(vararg a: Pair<Long, Int>): Map<Long, Int> = mapOf(*a)
fun mmoli(vararg a: Pair<Long, Int>): MutableMap<Long, Int> = mutableMapOf(*a)
fun moll(vararg a: Pair<Long, Long>): Map<Long, Long> = mapOf(*a)
fun mmoll(vararg a: Pair<Long, Long>): MutableMap<Long, Long> = mutableMapOf(*a)
fun molp(vararg a: Pair<Long, Point>): Map<Long, Point> = mapOf(*a)
fun mmolp(vararg a: Pair<Long, Point>): MutableMap<Long, Point> = mutableMapOf(*a)
fun molp3(vararg a: Pair<Long, Point3D>): Map<Long, Point3D> = mapOf(*a)
fun mmolp3(vararg a: Pair<Long, Point3D>): MutableMap<Long, Point3D> = mutableMapOf(*a)
fun mola(vararg a: Pair<Long, Any>): Map<Long, Any> = mapOf(*a)
fun mmola(vararg a: Pair<Long, Any>): MutableMap<Long, Any> = mutableMapOf(*a)

fun mopi(vararg a: Pair<Point, Int>): Map<Point, Int> = mapOf(*a)
fun mmopi(vararg a: Pair<Point, Int>): MutableMap<Point, Int> = mutableMapOf(*a)
fun mopl(vararg a: Pair<Point, Long>): Map<Point, Long> = mapOf(*a)
fun mmopl(vararg a: Pair<Point, Long>): MutableMap<Point, Long> = mutableMapOf(*a)
fun mopp(vararg a: Pair<Point, Point>): Map<Point, Point> = mapOf(*a)
fun mmopp(vararg a: Pair<Point, Point>): MutableMap<Point, Point> = mutableMapOf(*a)
fun mopp3(vararg a: Pair<Point, Point3D>): Map<Point, Point3D> = mapOf(*a)
fun mmopp3(vararg a: Pair<Point, Point3D>): MutableMap<Point, Point3D> = mutableMapOf(*a)
fun mopa(vararg a: Pair<Point, Any>): Map<Point, Any> = mapOf(*a)
fun mmopa(vararg a: Pair<Point, Any>): MutableMap<Point, Any> = mutableMapOf(*a)

fun mop3i(vararg a: Pair<Point3D, Int>): Map<Point3D, Int> = mapOf(*a)
fun mmop3i(vararg a: Pair<Point3D, Int>): MutableMap<Point3D, Int> = mutableMapOf(*a)
fun mop3l(vararg a: Pair<Point3D, Long>): Map<Point3D, Long> = mapOf(*a)
fun mmop3l(vararg a: Pair<Point3D, Long>): MutableMap<Point3D, Long> = mutableMapOf(*a)
fun mop3p(vararg a: Pair<Point3D, Point>): Map<Point3D, Point> = mapOf(*a)
fun mmop3p(vararg a: Pair<Point3D, Point>): MutableMap<Point3D, Point> = mutableMapOf(*a)
fun mop3p3(vararg a: Pair<Point3D, Point3D>): Map<Point3D, Point3D> = mapOf(*a)
fun mmop3p3(vararg a: Pair<Point3D, Point3D>): MutableMap<Point3D, Point3D> = mutableMapOf(*a)
fun mop3a(vararg a: Pair<Point3D, Any>): Map<Point3D, Any> = mapOf(*a)
fun mmop3a(vararg a: Pair<Point3D, Any>): MutableMap<Point3D, Any> = mutableMapOf(*a)

fun moai(vararg a: Pair<Any, Int>): Map<Any, Int> = mapOf(*a)
fun mmoai(vararg a: Pair<Any, Int>): MutableMap<Any, Int> = mutableMapOf(*a)
fun moal(vararg a: Pair<Any, Long>): Map<Any, Long> = mapOf(*a)
fun mmoal(vararg a: Pair<Any, Long>): MutableMap<Any, Long> = mutableMapOf(*a)
fun moap(vararg a: Pair<Any, Point>): Map<Any, Point> = mapOf(*a)
fun mmoap(vararg a: Pair<Any, Point>): MutableMap<Any, Point> = mutableMapOf(*a)
fun moap3(vararg a: Pair<Any, Point3D>): Map<Any, Point3D> = mapOf(*a)
fun mmoap3(vararg a: Pair<Any, Point3D>): MutableMap<Any, Point3D> = mutableMapOf(*a)
fun moaa(vararg a: Pair<Any, Any>): Map<Any, Any> = mapOf(*a)
fun mmoaa(vararg a: Pair<Any, Any>): MutableMap<Any, Any> = mutableMapOf(*a)

fun mloa(): MutableList<Any> = mutableListOf()
fun <T> mlot(): MutableList<T> = mutableListOf()

fun loi(vararg a: Int): List<Int> = listOf(*a.toTypedArray())
fun mloi(vararg a: Int): MutableList<Int> = mutableListOf(*a.toTypedArray())
fun lol(vararg a: Long): List<Long> = listOf(*a.toTypedArray())
fun mlol(vararg a: Long): MutableList<Long> = mutableListOf(*a.toTypedArray())
fun lop(vararg a: Point): List<Point> = listOf(*a)
fun mlop(vararg a: Point): MutableList<Point> = mutableListOf(*a)
fun lop3(vararg a: Point3D): List<Point3D> = listOf(*a)
fun mlop3(vararg a: Point3D): MutableList<Point3D> = mutableListOf(*a)
fun aoi(size: Int): IntArray = IntArray(size)
fun aoi(size: Int, value:Int): IntArray = IntArray(size).apply { fill(value) }
fun aod(size: Int): DoubleArray = DoubleArray(size)
fun aod(size: Int, value:Double): DoubleArray = DoubleArray(size).apply { fill(value) }
fun aol(size: Int): LongArray = LongArray(size)
fun aol(size: Int, value:Long): LongArray = LongArray(size).apply { fill(value) }
